# Generated by Django 5.2.7 on 2025-10-24 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateTimeField()),
                ('orderStatus', models.TextField()),
                ('totalPrice', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('name', models.TextField()),
                ('phone', models.TextField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProviderEditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifiedTimestamp', models.DateTimeField()),
                ('productID', models.TextField()),
                ('email', models.TextField()),
                ('modifiedType', models.TextField(blank=True, null=True)),
                ('productDelName', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPrice', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transferSlip', models.TextField(blank=True, null=True)),
                ('paymentDate', models.DateTimeField()),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.order')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('productID', models.TextField(primary_key=True, serialize=False)),
                ('productName', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('addedDate', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('size', models.TextField(blank=True, null=True)),
                ('material', models.TextField(blank=True, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgURL', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productdetail')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optionType', models.TextField()),
                ('optionName', models.TextField()),
                ('addPrice', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('image', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productdetail')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customValue', models.TextField(blank=True, null=True)),
                ('quantities', models.PositiveIntegerField()),
                ('eachTotalPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productName', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productdetail')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.productoption')),
            ],
        ),
        migrations.CreateModel(
            name='OptionCustom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(blank=True, null=True)),
                ('attachedIMG', models.TextField(blank=True, null=True)),
                ('customType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.customtype')),
                ('orderItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.orderitem')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.productoption')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderList',
            fields=[
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.userinfo')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userinfo'),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subName', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='main.productcategory')),
            ],
        ),
        migrations.AddField(
            model_name='productdetail',
            name='subcategories',
            field=models.ManyToManyField(related_name='products', to='main.subcategory'),
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('phone', models.TextField(blank=True, null=True)),
                ('address', models.TextField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantities', models.PositiveIntegerField()),
                ('customValue', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productdetail')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userinfo')),
            ],
            options={
                'unique_together': {('email', 'product', 'customValue')},
            },
        ),
    ]
