# Generated by Django 5.2.7 on 2025-10-28 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_productdetail_updateddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='optioncustom',
            name='attachedIMG',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/custom_products/'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.productdetail'),
        ),
        migrations.CreateModel(
            name='CustomProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(blank=True, max_length=50, null=True)),
                ('keyColor', models.CharField(blank=True, null=True)),
                ('textColor', models.CharField(blank=True, null=True)),
                ('customText', models.CharField(blank=True, max_length=10, null=True)),
                ('customImage', models.ImageField(blank=True, null=True, upload_to='uploads/custom_products/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_products', to='main.productcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_products', to='main.userinfo')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='custom_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='main.customproduct'),
        ),
    ]
