# Generated by Django 5.2.7 on 2025-10-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_productcategory_description_subcategory_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/user_profiles/'),
        ),
    ]
