# Generated by Django 5.2.7 on 2025-10-28 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_userinfo_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercart',
            name='custom_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customproduct'),
        ),
        migrations.AlterField(
            model_name='customercart',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.productdetail'),
        ),
    ]
