# Generated by Django 5.2.7 on 2025-10-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_customercart_custom_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='parcelStatus',
            field=models.TextField(default='รอตรวจสอบ'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='district',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='postal_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='province',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='subdistrict',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderStatus',
            field=models.TextField(default='รอตรวจสอบ'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
